// <auto-generated />
namespace ProductMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203051756019_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5d1NVtP2y9+8mQsjT9Kj8siI0Re5+X5e2K18xBYfWT7ox5PCbP2+s31KudebYeN34ra/V75dfABfUQtV3ndXr/Kz/Xds6cfpXfD9+52X7Svee+ge/pt2d7b+yh9sS7LbFLSB+dZ2eQfpatPH71uqzr/PF/mddbms5dZ2+Y1zcvZLGf0lQyPVp/ejhIP7+7sgRJ3s+WyarOWJrmHeAdN/GsQfd3WxC8fpc+Kd/nseb68aOcW2S+yd+YT+vWj9KtlQexFL7X1OvcHJ3/7nT6+6yajP0XENG1WEAUUIWKVqiqfTvB5/q7tTJe88zpvu7Oauj6EhcbuqxgytlvHpHeFSw033x1g58dfZKsV0cljb/0kfS28fbL9+v0ZeCEw7k4DDu0SyfZEjJNd5J1vqWvC9FlRN+3TrM0mGWbuZLboNbslkU1vmyQokDXzAn4PXnJy7ualA8bR8RkNbUESwKPUMRI2wxjwy6+nWZnVESk8qcr1YjkkyZveFuHw35dP+hAe3+3g3qWRJwPasqNPukTfxLPdJrZ3y7sdHn2s/HKzXu4xkDT5KCXSXBYzZp7rps0XYzQYv/5F5UlZ0Hhdgy+yZXGeN+2b6m0OG0P8/fV1u9VoTTMr/9+q4AsM/0ZV3tP/t1fMy8usns6zemuRvbvzTSrbvrr4BtStcMxnH80mFQ1AEP1gZdxn4Md3fffj8dO8KS4cCDgjy3wKE+iAmjZny/PKkJsG52NkmnRm44u8zWZEo+O6Lc6zaUtfT/OmYXP5k1m5piani0k+O1t+uW5X6/a4afLFpLz2x/v47ub+2eKEOD/+coW/PIn9+kMgNAsaQv7l8sm6KGcW72d9bhwCAXZRFiesyF0gcBfXFtKLanlLQEq+p/kqX0JA3uSLVUnAmi+Xr7PLfBi3m2kYUuzx0yK7qLOFT0H5xLgbGfXsdUEd+G+4/uhPYlfyfY/+nwAAAP//P9ftwnALAAA="; }
        }
    }
}
