// <auto-generated />
namespace ProductMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddEmailProduct : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203051909076_AddEmailProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5d1NVtP2y9+8mQsjT9Kj8siI0Re5+X5e2K18xBYfWT7ox5PCbP2+s31KudebYeN34ra/V75dfABfUQtV3ndXr/Kz/Xds6cfpXfD9+52X7Svee+ge/pt2d7b+yh9sS7LbFLSB+dZ2eQfpatPH71uqzr/PF/mddbms5dZ2+Y1zcvZLGf0lQyPVp/ejhIP7+7sgRJ3s+WyarOWJrmHeAdN/GsQfd3WxC8fpc+Kd/nseb68aOcW2S+yd+YT+vWj9KtlQexFL7X1OvcHJ39v7vR0kRXlz3Kvj+86FugzBrFqmxVEd8WIGLSqyqcTfJ6/aztMIu+8ztsuL6WuD2Hcsfsqhozt1onGXZENI0N3B4To8RfZakV08oRKP0lfi0SdbL9+f7FZCIy700AuukSyPRG7Zhd551vqmjB9VtRN+zRrs0mGmTuZLXrNbklk09smuQ0k3LyA34OXnHZx89IB4+j4jIa2ILnjUeoYCZthDPjl19OszOqI7J9U5XqxHNIfm94WkfTfl09uD0HlywehH/VhPL7bGX+Xzp4cacuOJuxO3Ca+7zaxvVv+7/D5Y+W5my1KjwmlyUcpEeeymDEDXjdtvhijwfj1LypPyoLG6xp8kS2L87xp31Rvc1hHkpGvb5WsLm6aWfn/VtNUYPg3GqGe5bq9SVleZvV0ntVbi+zdnQ8yE+8B6f1Uf195fQPKX3jvs49mk4oGIIh+sGnoi8Lju74L9vhp3hQXDgQcsmU+hRvggJo2Z8vzytCbBudjZJp0puOLvM1mRKPjui3Os2lLX0/zpmHj/ZNZueYZm+Szs+WX63a1bo+bJl9Mymt/vI/vbu6f7V+I8+MvV/jLk/2vPwRCs6Ah5F8un6yLcmbxftbn6yEQYBcVFsKKnBcCd3FtIb2olrcEpOR7mq/yJUTtTb5YlQSs+XL5OrvMh3G7mYYhxR4/LbKLOlv4FJRPjPOTUc9eF9SB/4brj/4kdiX//+j/CQAA///4udTGdAwAAA=="; }
        }
    }
}
